import { ScanOptions, TransformOptions } from '@models/settings.model';

export const DEFAULT_HARD_EXCLUDES: readonly string[] = [
  '.git',
  '.git-hooks',
  '.github',
  '.gitlab',
  '.idea',
  '.vscode',
  '.devcontainer',
  'node_modules',
  'bower_components',
  '.angular',
  '.svelte-kit',
  '.next',
  '.vite',
  '.nuxt',
  '.turbo',
  '.expo',
  '.cache',
  '.yarn',
  '.pnpm-store',
  'build',
  'dist',
  'out',
  'target',
  'bin',
  'obj',
  'release',
  'debug',
  '__pycache__',
  '.pytest_cache',
  '.mypy_cache',
  '.ruff_cache',
  '.venv',
  'venv',
  'env',
  '.env',
  'tmp',
  'temp',
  'coverage',
  'htmlcov',
  'icon_data.py',
];

export const DEFAULT_BINARY_EXTENSIONS: readonly string[] = [
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.bmp',
  '.tiff',
  '.tif',
  '.psd',
  '.ai',
  '.eps',
  '.raw',
  '.heic',
  '.heif',
  '.svg',
  '.pdf',
  '.epub',
  '.mobi',
  '.djvu',
  '.docx',
  '.doc',
  '.xlsx',
  '.xls',
  '.pptx',
  '.ppt',
  '.parquet',
  '.arrow',
  '.safetensors',
  '.pt',
  '.pth',
  '.onnx',
  '.tflite',
  '.h5',
  '.pkl',
  '.bin',
  '.dat',
  '.exe',
  '.dll',
  '.so',
  '.dylib',
  '.wasm',
  '.class',
  '.pyc',
  '.pyo',
  '.pyd',
  '.o',
  '.obj',
  '.lib',
  '.a',
  '.rlib',
  '.rmeta',
  '.pdb',
  '.whl',
  '.zip',
  '.tar',
  '.gz',
  '.tgz',
  '.bz2',
  '.xz',
  '.rar',
  '.7z',
  '.iso',
  '.dmg',
  '.msi',
  '.pkg',
  '.mp3',
  '.mp4',
  '.wav',
  '.avi',
  '.mov',
  '.mkv',
  '.flv',
  '.webm',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.otf',
  '.db',
  '.sqlite',
  '.sqlite3',
];

export const DEFAULT_LOCKFILES_EXCLUDES: readonly string[] = [
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'go.sum',
  'Cargo.lock',
  'poetry.lock',
  'Pipfile.lock',
  'composer.lock',
  'Gemfile.lock',
];

export const MAX_WEB_FILE_SIZE_BYTES = 1024 * 1024 * 1.5;
export const MAX_SINGLE_LINE_LENGTH = 4000;
export const MAX_PREVIEW_LENGTH = 120000;

export const STORAGE_KEY_SCAN = 'codecontext_scan_options';
export const STORAGE_KEY_TRANSFORM = 'codecontext_transform_options';
export const STORAGE_KEY_THEME = 'codecontext_theme';

export const FALLBACK_SCAN_OPTIONS: ScanOptions = {
  use_gitignore: true,
  ignore_binary: true,
  ignore_lockfiles: true,
  whitelist_extensions: [],
  manual_excludes: [...DEFAULT_HARD_EXCLUDES],
  gitignore_disabled_rules: [],
  binary_extensions: [...DEFAULT_BINARY_EXTENSIONS],
  lockfiles_excludes: [...DEFAULT_LOCKFILES_EXCLUDES],
  output_file_path: null,
  auto_watch: false,
};

export const FALLBACK_TRANSFORM_OPTIONS: TransformOptions = {
  strip_comments: false,
  compress_whitespace: false,
  sanitize_secrets: false,
  skeleton_mode: false,
  xml_format: true,
  always_send_full_tree: false,
  auto_watch: false,
  system_prompt: '',
  comment_rules_json: null,
  max_token_budget: null,
  git_diff_mode: false,
  git_diff_context_lines: 3,
  git_diff_text: null,
};
